import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,AlertTriangle,CheckCircle2,Clock3,ExternalLink,Pause,Play,Plus,RefreshCw,RotateCcw,Server,Square,WifiOff} from 'lucide-react';
import CommentGroups from './CommentGroups.jsx';
import {DesktopStatus,NextJob,AutomationPanel,LogsPanel,SettingsPanel,FacebookDesktop} from './DesktopPanels.jsx';
import './styles.css';

const API=import.meta.env.VITE_API_BASE||'';
async function req(path,opt={}){if(window.simiDesktop){const r=await window.simiDesktop.requestApi(path,{method:opt.method,body:opt.body});if(r.status===204)return null;if(!r.ok)throw new Error(r.data?.error||`Máy chủ trả về lỗi ${r.status}`);return r.data}let r;try{r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt})}catch{throw new Error('Không thể kết nối máy chủ')}if(r.status===204)return null;const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Máy chủ trả về lỗi ${r.status}`);return d}
const fmt=v=>v?new Date(v).toLocaleString('vi-VN'):'—';
const localInput=()=>{const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return d.toISOString().slice(0,16)};
const statusText={PENDING:'Chờ chạy',RETRY_DUE:'Chờ chạy lại',RUNNING:'Đang chạy',SUCCESS:'Đã bình luận',FAILED:'Lỗi',SKIPPED:'Đã chạy thử',PAUSED:'Tạm dừng',CANCELLED:'Đã hủy',UNKNOWN:'Chưa đăng nhập',READY:'Sẵn sàng',SESSION_EXPIRED:'Hết phiên đăng nhập',CHECKPOINT:'Cần xác minh',DISABLED:'Đang tắt',ONLINE:'Hoạt động',OFFLINE:'Mất kết nối',WARNING:'Cảnh báo'};
const statusKind=v=>({SUCCESS:'good',READY:'good',ONLINE:'good',SKIPPED:'info',RUNNING:'info',PENDING:'wait',RETRY_DUE:'wait',UNKNOWN:'wait',WARNING:'wait',FAILED:'bad',OFFLINE:'bad',SESSION_EXPIRED:'bad',CHECKPOINT:'bad',DISABLED:'muted',PAUSED:'muted',CANCELLED:'muted'}[v]||'muted');
const COMMENT_PRESETS=[
 {group:'Hỏi thông tin',items:['Sản phẩm này còn hàng không ạ?','Cho mình xin thêm thông tin chi tiết với ạ.','Mình muốn được tư vấn thêm về sản phẩm này.','Sản phẩm này có bảo hành không ạ?']},
 {group:'Hỏi giá & giao hàng',items:['Cho mình xin giá sản phẩm này với ạ.','Có giao hàng toàn quốc không ạ?','Phí giao hàng về tỉnh là bao nhiêu ạ?','Hiện sản phẩm này có ưu đãi gì không ạ?']},
 {group:'Thể hiện quan tâm',items:['Mình đang quan tâm sản phẩm này, shop tư vấn giúp nhé.','Mẫu này nhìn đẹp quá, cho mình xin thông tin ạ.','Shop kiểm tra tin nhắn giúp mình nhé.','Mình muốn đặt sản phẩm này thì làm thế nào ạ?']}
];
function Badge({value,label}){return <span className={`badge ${statusKind(value)}`}>{label||statusText[value]||value}</span>}
function Panel({title,description,action,children}){return <section className="panel"><div className="panel-head"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</div>{children}</section>}
function Table({heads,children,empty='Chưa có dữ liệu'}){return <div className="table-wrap"><table><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{children||<tr><td colSpan={heads.length} className="empty">{empty}</td></tr>}</tbody></table></div>}
function Field({label,hint,children}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}

function App(){
 const [tab,setTab]=useState('overview');const [data,setData]=useState({dash:{},campaigns:[],accounts:[],posts:[],templates:[],groups:[],jobs:[],workers:[],system:null});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 async function load(silent=true){if(!silent)setLoading(true);setError('');try{const [dash,campaigns,accounts,posts,templates,groups,jobs,workers]=await Promise.all(['/api/dashboard','/api/campaigns','/api/accounts','/api/posts','/api/templates','/api/comment-groups','/api/jobs?limit=150','/api/workers'].map(req));setData(prev=>({...prev,dash,campaigns,accounts,posts,templates,groups,jobs,workers}));req('/api/system-status').then(system=>setData(prev=>({...prev,system}))).catch(()=>{})}catch(e){setError(e.message)}finally{if(!silent)setLoading(false)}}
 useEffect(()=>{load(false)},[]);
 useEffect(()=>{const timer=setInterval(()=>req('/api/dashboard').then(dash=>setData(p=>({...p,dash}))).catch(()=>{}),10000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{const fast=data.jobs.some(j=>j.status==='RUNNING');const timer=setInterval(()=>req('/api/jobs?limit=150').then(jobs=>setData(p=>({...p,jobs}))).catch(()=>{}),fast?2500:10000);return()=>clearInterval(timer)},[data.jobs.some(j=>j.status==='RUNNING')]);
 useEffect(()=>{const timer=setInterval(()=>req('/api/system-status').then(system=>setData(p=>({...p,system}))).catch(()=>{}),30000);return()=>clearInterval(timer)},[]);
 const tell=m=>{setNotice(m);setTimeout(()=>setNotice(''),4000)};
 const desktop=!!window.simiDesktop;
 const nav=[['overview','Tổng quan'],['posts','Bài viết'],['accounts','Facebook'],['templates','Bình luận'],['campaigns','Chiến dịch'],['jobs','Hàng chờ'],['system','Hệ thống'],...(desktop?[['automation','Automation'],['logs','Nhật ký'],['settings','Cài đặt']]:[])];
 const localTab=['automation','logs','settings'].includes(tab);
 return <div className={desktop?'desktop-frame':'shell'}>
  {desktop&&<aside className="desktop-sidebar"><div className="desktop-logo"><span>SIMI</span><b>Automation</b></div><nav>{nav.map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</nav><DesktopStatus/></aside>}
  <div className={desktop?'desktop-workspace':''}>
   <header><div><div className="brand">SIMI AUTOMATION</div><h1>{desktop?nav.find(([key])=>key===tab)?.[1]:'Quản lý bình luận Facebook'}</h1><p>{desktop?'Trung tâm điều khiển trên máy Mac':'Điều phối nội dung, tài khoản và lịch bình luận tại một nơi.'}</p></div><button className="secondary" onClick={()=>load(true)} disabled={loading}><RefreshCw size={16} className={loading?'spin':''}/>Làm mới</button></header>
   {data.system?.dryRun&&<div className="trial"><AlertTriangle size={17}/><div><b>CHẾ ĐỘ THỬ NGHIỆM</b><span>Hệ thống chỉ mở bài và nhập nội dung, không gửi bình luận.</span></div></div>}
   {error&&<div className="alert error"><WifiOff size={17}/><div><b>Không thể kết nối API</b><span>{error}</span></div></div>}{notice&&<div className="alert success"><CheckCircle2 size={17}/>{notice}</div>}
   {!desktop&&<nav>{nav.map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</nav>}
   <main>{loading&&!error&&!localTab&&<div className="loading">Đang tải dữ liệu…</div>}
    {(!loading&&!error||localTab)&&<>{tab==='overview'&&<>{desktop&&<NextJob jobs={data.jobs} go={setTab}/>}<Overview {...data} go={setTab}/></>}{tab==='posts'&&<Posts {...data} reload={load} tell={tell}/>}{tab==='accounts'&&(desktop?<FacebookDesktop accounts={data.accounts} reload={load}><Accounts rows={data.accounts} reload={load} tell={tell}/></FacebookDesktop>:<Accounts rows={data.accounts} reload={load} tell={tell}/>)}{tab==='templates'&&<CommentGroups campaigns={data.campaigns} groups={data.groups} templates={data.templates} reload={load} tell={tell}/>}{tab==='campaigns'&&<Campaigns rows={data.campaigns} reload={load} tell={tell}/>}{tab==='jobs'&&<Jobs jobs={data.jobs} reload={load} tell={tell}/>}{tab==='system'&&<System data={data.system||{}} reload={load} tell={tell}/>}{tab==='automation'&&desktop&&<AutomationPanel/>}{tab==='logs'&&desktop&&<LogsPanel/>}{tab==='settings'&&desktop&&<SettingsPanel/>}</>}
   </main>
  </div>
 </div>
}
function Overview({dash,jobs,campaigns,accounts,templates,posts,go}){const cards=[['Chiến dịch đang chạy',dash.activeCampaigns],['Tài khoản đang hoạt động',dash.activeAccounts],['Bài viết đang theo dõi',dash.enabledPosts],['Đang chờ bình luận',dash.pendingJobs],['Đã bình luận hôm nay',dash.successToday],['Lỗi hôm nay',dash.failedToday]];const recent=jobs.slice(0,12);const next=dash.nextJobs||[];const steps=[['1','Tạo chiến dịch',campaigns.length>0,'campaigns'],['2','Thêm tài khoản Facebook',accounts.length>0,'accounts'],['3','Soạn nội dung bình luận',templates.length>0,'templates'],['4','Thêm bài và tạo lịch',posts.length>0,'posts']];return <><section className="quick-start"><div><span className="eyebrow">BẮT ĐẦU NHANH</span><h2>Thiết lập một lượt bình luận</h2><p>Làm lần lượt từ trái sang phải. Dữ liệu tự làm mới mỗi 15 giây.</p></div><div className="step-grid">{steps.map(([n,label,done,target])=><button key={n} className={`step-card ${done?'done':''}`} onClick={()=>go(target)}><span>{done?'✓':n}</span><b>{label}</b><small>{done?'Đã sẵn sàng':'Thực hiện bước này'}</small></button>)}</div></section><section className="cards">{cards.map(([l,v])=><article className="metric" key={l}><span>{l}</span><strong>{v??0}</strong></article>)}</section><Panel title="Lịch sắp chạy" description="Biết trước thời gian, tài khoản và nội dung sẽ được dùng." action={<button className="secondary" onClick={()=>go('jobs')}><Clock3 size={15}/>Mở hàng chờ</button>}><div className="upcoming-list">{next.length?next.map((j,i)=><article key={j.id} className={i===0?'next':''}><div className="upcoming-time"><Clock3 size={16}/><b>{j.status==='RUNNING'?'Đang chạy':fmt(j.scheduled_at)}</b><span>{i===0?'Lượt tiếp theo':`Lượt ${i+1}`}</span></div><div><b>{j.account_name}</b><span>{j.post_label||'Bài Facebook'}</span></div><p>{j.comment_text}</p><Badge value={j.dry_run?'WARNING':j.status} label={j.dry_run?'Chạy thử':statusText[j.status]}/></article>):<div className="empty-state"><CheckCircle2 size={22}/><b>Chưa có lượt nào sắp chạy</b><span>Vào Bài viết để tạo lịch mới.</span></div>}</div></Panel><Panel title="Hoạt động gần đây" description="Kết quả mới nhất từ dữ liệu thực của hệ thống."><Table heads={['Thời gian','Tài khoản','Bài viết','Nội dung','Trạng thái']}>{recent.length?recent.map(j=><tr key={j.id}><td>{fmt(j.finished_at||j.started_at||j.scheduled_at)}</td><td>{j.account_name}</td><td>{j.post_label||`Bài #${j.post_id}`}</td><td className="comment">{j.comment_text}</td><td><Badge value={j.status}/></td></tr>):null}</Table></Panel></>}

function Posts({posts,campaigns,accounts,templates,groups,reload,tell}){
 const [form,setForm]=useState({campaignId:'',postUrl:'',label:'',priority:100});const [schedule,setSchedule]=useState({postId:'',groupId:'',templateId:'',accountIds:[],startAt:localInput(),minGapMinutes:10,maxGapMinutes:30});const [preview,setPreview]=useState([]);const selected=useMemo(()=>posts.find(p=>String(p.id)===String(schedule.postId)),[posts,schedule.postId]);const availableGroups=useMemo(()=>groups.filter(g=>selected&&String(g.campaign_id)===String(selected.campaign_id)&&g.is_active),[groups,selected]);const availableTemplates=useMemo(()=>templates.filter(t=>String(t.group_id)===String(schedule.groupId)&&t.is_active),[templates,schedule.groupId]);
 async function add(){try{await req('/api/posts',{method:'POST',body:JSON.stringify(form)});setForm({...form,postUrl:'',label:''});tell('Đã thêm bài viết');reload()}catch(e){tell(e.message)}}
 async function createSchedule(){if(!schedule.postId||!schedule.groupId||!schedule.accountIds.length)return tell('Hãy chọn bài viết, nhóm nội dung và ít nhất một tài khoản sẵn sàng');if(selected&&!selected.is_enabled)return tell('Bài viết đang tạm dừng. Hãy bấm Bật bài này trước');try{const result=await req(`/api/posts/${schedule.postId}/assign-accounts`,{method:'POST',body:JSON.stringify({...schedule,startAt:new Date(schedule.startAt).toISOString()})});setPreview(result.assignments.map(x=>({...x,name:accounts.find(a=>a.id===x.accountId)?.name||`Tài khoản #${x.accountId}`})));tell('Đã tạo lịch bình luận');reload()}catch(e){tell(e.message)}}
 async function toggle(p){try{await req(`/api/posts/${p.id}`,{method:'PATCH',body:JSON.stringify({isEnabled:!p.is_enabled})});tell(p.is_enabled?'Đã tạm dừng bài viết':'Đã bật lại bài viết');await reload()}catch(e){tell(e.message)}}
 return <><section className="page-guide"><div className="guide-number">1</div><div><b>Thêm bài Facebook</b><span>Chọn chiến dịch và lưu đường dẫn bài cần bình luận.</span></div><div className="guide-line"/><div className="guide-number">2</div><div><b>Chọn tài khoản</b><span>Tick các tài khoản có trạng thái Sẵn sàng.</span></div><div className="guide-line"/><div className="guide-number">3</div><div><b>Tạo lịch</b><span>Chọn giờ bắt đầu rồi xem lịch ở Hàng chờ.</span></div></section><Panel title="Bước 1 · Thêm bài viết" description="Khai báo bài Facebook cần theo dõi và bình luận." action={<button onClick={add}><Plus size={15}/>Lưu bài viết</button>}><div className="form-grid four"><Field label="Chiến dịch"><select value={form.campaignId} onChange={e=>setForm({...form,campaignId:e.target.value})}><option value="">Chọn chiến dịch</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Đường dẫn bài Facebook"><input placeholder="https://www.facebook.com/..." value={form.postUrl} onChange={e=>setForm({...form,postUrl:e.target.value})}/></Field><Field label="Tên gợi nhớ"><input placeholder="Ví dụ: UNIQ Việt Nam" value={form.label} onChange={e=>setForm({...form,label:e.target.value})}/></Field><Field label="Độ ưu tiên" hint="Giữ 100 nếu không cần ưu tiên đặc biệt"><input type="number" value={form.priority} onChange={e=>setForm({...form,priority:+e.target.value})}/></Field></div></Panel>
 <Panel title="Bước 2–3 · Chọn nội dung, tài khoản và tạo lịch" description="Mọi thông tin sẽ chạy được hiển thị trước khi xác nhận." action={<button onClick={createSchedule}><Play size={15}/>Tạo lịch bình luận</button>}>
  <div className="schedule"><div className="schedule-settings">
   <Field label="1. Bài viết"><select value={schedule.postId} onChange={e=>{setSchedule({...schedule,postId:e.target.value,groupId:'',templateId:'',accountIds:[]});setPreview([])}}><option value="">{posts.length?'Chọn bài viết':'Chưa có bài viết nào'}</option>{posts.map(p=><option key={p.id} value={p.id}>{p.is_enabled?'':'[Tạm dừng] '}{p.label||p.post_url}</option>)}</select></Field>
   {selected&&!selected.is_enabled&&<div className="inline-warning"><div><b>Bài này đang tạm dừng</b><span>Bật lại để có thể tạo lịch.</span></div><button className="tiny" onClick={()=>toggle(selected)}>Bật bài này</button></div>}
   <Field label="2. Nhóm bình luận"><select value={schedule.groupId} disabled={!selected} onChange={e=>setSchedule({...schedule,groupId:e.target.value,templateId:''})}><option value="">Chọn nhóm nội dung</option>{availableGroups.map(g=><option key={g.id} value={g.id}>{g.name} · {g.template_count} câu</option>)}</select></Field>
   <Field label="3. Chọn câu" hint="Mặc định xoay vòng câu ít dùng trong nhóm."><select value={schedule.templateId} disabled={!schedule.groupId} onChange={e=>setSchedule({...schedule,templateId:e.target.value})}><option value="">Tự động chọn trong nhóm</option>{availableTemplates.map(t=><option key={t.id} value={t.id}>{t.content}</option>)}</select></Field>
   <Field label="4. Bắt đầu từ"><input type="datetime-local" value={schedule.startAt} onChange={e=>setSchedule({...schedule,startAt:e.target.value})}/></Field>
   <div className="two"><Field label="Khoảng cách tối thiểu (phút)"><input type="number" min="0" value={schedule.minGapMinutes} onChange={e=>setSchedule({...schedule,minGapMinutes:+e.target.value})}/></Field><Field label="Khoảng cách tối đa (phút)"><input type="number" min="0" value={schedule.maxGapMinutes} onChange={e=>setSchedule({...schedule,maxGapMinutes:+e.target.value})}/></Field></div>
   {selected&&<div className="selected"><b>{selected.label||'Bài viết chưa đặt tên'}</b><span>{selected.campaign_name} · {selected.is_enabled?'Đang hoạt động':'Đang tạm dừng'} · {schedule.templateId?'Dùng câu đã chọn':'Tự xoay vòng nội dung'}</span></div>}
  </div><div><h3>4. Tài khoản sẽ tham gia bình luận</h3><div className="account-grid">{accounts.map(a=>{const ready=a.session_status==='READY'&&a.is_active;const checked=schedule.accountIds.includes(a.id);return <label className={`${checked?'checked ':''}${!ready?'disabled':''}`} key={a.id}><input type="checkbox" disabled={!ready} checked={checked} onChange={e=>setSchedule({...schedule,accountIds:e.target.checked?[...schedule.accountIds,a.id]:schedule.accountIds.filter(id=>id!==a.id)})}/><div><b>{a.name}</b><small>{a.profile_key}</small></div><Badge value={a.is_active?a.session_status:'DISABLED'}/></label>})}</div>
   {preview.length>0&&<div className="preview"><h3>Lịch vừa tạo</h3>{preview.map(x=><div className="preview-job" key={x.accountId}><div><b>{x.name}</b><span>{x.commentText}</span></div><strong>{fmt(x.scheduledAt)}</strong></div>)}</div>}
  </div></div>
 </Panel>
 <Panel title="Danh sách bài viết" description="Bài tạm dừng vẫn được lưu; bật lại để tạo lịch."><Table heads={['Bài viết','Chiến dịch','Trạng thái','Số tài khoản','Đã bình luận','Đang chờ','Thao tác']}>{posts.length?posts.map(p=><tr key={p.id}><td><b>{p.label||'Chưa đặt tên'}</b><div className="muted truncate">{p.post_url}</div></td><td>{p.campaign_name}</td><td><Badge value={p.is_enabled?'READY':'PAUSED'} label={p.is_enabled?'Đang bật':'Tạm dừng'}/></td><td>{p.account_count}</td><td>{p.success_count}</td><td>{p.pending_count}</td><td><div className="actions"><a className="icon-btn" href={p.post_url} target="_blank" rel="noreferrer"><ExternalLink size={15}/></a><button className={`tiny ${p.is_enabled?'secondary':''}`} onClick={()=>toggle(p)}>{p.is_enabled?'Tạm dừng':'Bật lại'}</button></div></td></tr>):null}</Table></Panel></>
}

function Accounts({rows,reload,tell}){const [form,setForm]=useState({name:'',profileKey:'',dailyLimitOverride:''});async function add(){try{await req('/api/accounts',{method:'POST',body:JSON.stringify(form)});setForm({name:'',profileKey:'',dailyLimitOverride:''});tell('Đã thêm tài khoản Facebook');reload()}catch(e){tell(e.message)}}async function toggle(a){await req(`/api/accounts/${a.id}`,{method:'PATCH',body:JSON.stringify({isActive:!a.is_active})});reload()}return <Panel title="Tài khoản Facebook" description="Mỗi tài khoản liên kết với một phiên trình duyệt riêng." action={<button onClick={add}><Plus size={15}/>Thêm tài khoản</button>}><div className="form-grid three"><Field label="Tên tài khoản"><input placeholder="Facebook SIMI 01" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Mã phiên trình duyệt" hint="Mã này dùng để liên kết với phiên Facebook đã đăng nhập trên máy chạy Trình điều khiển Facebook."><input placeholder="simi_fb_01" value={form.profileKey} onChange={e=>setForm({...form,profileKey:e.target.value})}/></Field><Field label="Giới hạn bình luận/ngày"><input type="number" min="1" placeholder="10" value={form.dailyLimitOverride} onChange={e=>setForm({...form,dailyLimitOverride:e.target.value})}/></Field></div><Table heads={['Tên tài khoản','Mã phiên','Trạng thái đăng nhập','Số bài được gán','Đã chạy hôm nay','Giới hạn/ngày','Thao tác']}>{rows.length?rows.map(a=><tr key={a.id}><td><b>{a.name}</b></td><td><code>{a.profile_key}</code></td><td><Badge value={a.is_active?a.session_status:'DISABLED'}/></td><td>{a.assigned_posts}</td><td>{a.success_today}</td><td>{a.daily_limit_override||'Theo chiến dịch'}</td><td><button className="tiny secondary" onClick={()=>toggle(a)}>{a.is_active?'Tắt':'Bật lại'}</button></td></tr>):null}</Table></Panel>}

function Templates({campaigns,rows,reload,tell}){
 const [form,setForm]=useState({campaignId:'',content:'',weight:1});const [saving,setSaving]=useState(false);
 async function add(){if(!form.campaignId)return tell('Hãy chọn chiến dịch trước');if(!form.content.trim())return tell('Hãy nhập hoặc chọn một nội dung bình luận');setSaving(true);try{await req('/api/templates',{method:'POST',body:JSON.stringify(form)});setForm({...form,content:''});tell('Đã lưu nội dung bình luận');reload()}catch(e){tell(e.message)}finally{setSaving(false)}}
 return <><Panel title="Soạn nội dung bình luận" description="Chọn một câu gợi ý hoặc tự viết, sau đó chỉnh lại cho phù hợp trước khi lưu." action={<button onClick={add} disabled={saving}><Plus size={15}/>{saving?'Đang lưu…':'Lưu nội dung'}</button>}><div className="composer"><Field label="1. Chọn chiến dịch"><select value={form.campaignId} onChange={e=>setForm({...form,campaignId:e.target.value})}><option value="">Chọn chiến dịch</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="2. Nội dung sẽ sử dụng" hint="Bạn có thể sửa lại câu gợi ý trước khi lưu."><textarea rows="3" placeholder="Nhập nội dung đã được duyệt" value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></Field><Field label="3. Mức ưu tiên" hint="Số càng cao thì câu này càng dễ được chọn."><input type="number" min="1" value={form.weight} onChange={e=>setForm({...form,weight:+e.target.value})}/></Field></div></Panel><Panel title="Câu bình luận gợi ý" description="Bấm vào một câu để đưa lên ô soạn thảo. Hệ thống không tự lưu cho đến khi bạn xác nhận."><div className="preset-groups">{COMMENT_PRESETS.map(group=><section key={group.group}><h3>{group.group}</h3><div className="preset-list">{group.items.map(item=><button className="preset" key={item} onClick={()=>setForm({...form,content:item})}>{item}</button>)}</div></section>)}</div></Panel><Panel title="Nội dung đã lưu" description={`${rows.length} nội dung đang có trong hệ thống.`}><Table heads={['Nội dung','Chiến dịch','Mức ưu tiên','Số lần đã dùng','Trạng thái']}>{rows.length?rows.map(x=><tr key={x.id}><td className="comment">{x.content}</td><td>{x.campaign_name}</td><td>{x.weight}</td><td>{x.usage_count}</td><td><Badge value={x.is_active?'READY':'DISABLED'} label={x.is_active?'Đang sử dụng':'Đang tắt'}/></td></tr>):null}</Table></Panel></>
}

function Campaigns({rows,reload,tell}){const [form,setForm]=useState({name:'',cooldownMinutes:180,maxCommentsPerAccountPerDay:8,dryRun:true});async function add(){try{await req('/api/campaigns',{method:'POST',body:JSON.stringify(form)});setForm({...form,name:''});tell('Đã tạo chiến dịch');reload()}catch(e){tell(e.message)}}async function patch(id,body){await req(`/api/campaigns/${id}`,{method:'PATCH',body:JSON.stringify(body)});reload()}return <Panel title="Chiến dịch" description="Quản lý giới hạn và chế độ vận hành cho từng đợt bình luận." action={<button onClick={add}><Plus size={15}/>Tạo chiến dịch</button>}><div className="form-grid four"><Field label="Tên chiến dịch"><input placeholder="Chiến dịch 10.10" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Thời gian nghỉ giữa các lượt (phút)"><input type="number" value={form.cooldownMinutes} onChange={e=>setForm({...form,cooldownMinutes:+e.target.value})}/></Field><Field label="Giới hạn bình luận/ngày"><input type="number" value={form.maxCommentsPerAccountPerDay} onChange={e=>setForm({...form,maxCommentsPerAccountPerDay:+e.target.value})}/></Field><Field label="Chế độ thử nghiệm" hint="Chỉ nhập nội dung, không gửi bình luận."><label className="switch"><input type="checkbox" checked={form.dryRun} onChange={e=>setForm({...form,dryRun:e.target.checked})}/><span>{form.dryRun?'Đang bật':'Đang tắt'}</span></label></Field></div><Table heads={['Chiến dịch','Giới hạn/ngày','Chế độ thử nghiệm','Trạng thái','Khung giờ','Thao tác']}>{rows.length?rows.map(c=><tr key={c.id}><td><b>{c.name}</b></td><td>{c.max_comments_per_account_per_day}</td><td><Badge value={c.dry_run?'WARNING':'READY'} label={c.dry_run?'Chạy thử':'Chạy thật'}/></td><td><Badge value={c.is_active?'READY':'DISABLED'} label={c.is_active?'Đang chạy':'Tạm dừng'}/></td><td>{c.window_count}</td><td><div className="actions"><button className="tiny secondary" onClick={()=>patch(c.id,{dryRun:!c.dry_run})}>{c.dry_run?'Cho phép gửi':'Bật chạy thử'}</button><button className="tiny secondary" onClick={()=>patch(c.id,{isActive:!c.is_active})}>{c.is_active?'Tạm dừng':'Bật lại'}</button></div></td></tr>):null}</Table></Panel>}

function JobsLegacy({jobs,reload,tell}){return null}

const STAGES=['OPENING_BROWSER','NAVIGATING','LOCATING_COMMENT_BOX','TYPING','SUBMITTING','VERIFYING','SUCCESS'];
const stageVi={OPENING_BROWSER:'Mở trình duyệt',NAVIGATING:'Mở bài viết',LOCATING_COMMENT_BOX:'Tìm ô bình luận',TYPING:'Nhập nội dung',SUBMITTING:'Đang gửi',VERIFYING:'Xác minh',SUCCESS:'Thành công'};
function Jobs({jobs,reload,tell}){
 const [selected,setSelected]=useState('');const [preflight,setPreflight]=useState(null);const [confirming,setConfirming]=useState(false);const [sending,setSending]=useState(false);
 useEffect(()=>{if(!selected){setPreflight(null);return}req(`/api/live-test/${selected}/preflight`).then(setPreflight).catch(e=>{setPreflight(null);tell(e.message)})},[selected,jobs.find(j=>j.id===selected)?.status]);
 async function dispatch(){setSending(true);try{await req(`/api/live-test/${selected}/execute`,{method:'POST',body:'{}'});tell('Đã giao đúng 1 job cho workflow 02');setConfirming(false);await reload()}catch(e){tell(e.message)}finally{setSending(false)}}
 const chosen=jobs.find(j=>j.id===selected);
 return <><Panel title="Hàng chờ bình luận" description="Chọn đúng một job PENDING, kiểm tra trước rồi mới gửi thử 1 bình luận." action={<button disabled={!preflight?.eligible||sending} onClick={()=>setConfirming(true)}><Play size={15}/>Gửi thử 1 bình luận</button>}><Table heads={['Chọn','Thời gian','Tài khoản','Bài viết','Nội dung','Tiến trình','Trạng thái']}>{jobs.length?jobs.map(j=>{const index=STAGES.indexOf(j.execution_stage);return <tr key={j.id}><td><input aria-label="Chọn job" type="radio" name="live-job" disabled={j.status!=='PENDING'} checked={selected===j.id} onChange={()=>setSelected(j.id)}/></td><td>{fmt(j.scheduled_at)}</td><td><b>{j.account_name}</b><div className="muted">{j.profile_key}</div></td><td>{j.post_label||`Bài #${j.post_id}`}</td><td className="comment">{j.comment_text}</td><td><div className={`stage ${j.status==='RUNNING'?'pulse':''}`}><span>{stageVi[j.execution_stage]||'Đang chờ'}</span><div>{STAGES.map((s,i)=><i key={s} className={i<=index?'done':''}/>)}</div></div></td><td><Badge value={j.status}/>{j.error_code&&<div className="error-code">{j.error_code}</div>}</td></tr>}):null}</Table>{preflight&&<div className={`preflight ${preflight.eligible?'ok':'blocked'}`}><b>{preflight.eligible?'Sẵn sàng CHẠY THẬT':'Chưa thể gửi thật'}</b><span>API: {preflight.apiDryRun?'CHẠY THỬ':'CHẠY THẬT'} · Worker: {preflight.workerDryRun?'CHẠY THỬ':'CHẠY THẬT'} · Chiến dịch: {preflight.campaignDryRun?'CHẠY THỬ':'CHẠY THẬT'}</span>{preflight.reasons?.map(x=><small key={x}>• {x}</small>)}</div>}</Panel>{confirming&&chosen&&<div className="modal-backdrop" onKeyDown={e=>{if(e.key==='Enter')e.preventDefault()}}><div className="confirm-modal" role="dialog" aria-modal="true"><h2>Xác nhận gửi thật 1 bình luận</h2><p>Enter không xác nhận thao tác này. Hãy kiểm tra từng thông tin.</p><dl><dt>Tài khoản</dt><dd>{chosen.account_name} ({chosen.profile_key})</dd><dt>Bài viết</dt><dd>{chosen.post_label||chosen.post_url}</dd><dt>Nội dung</dt><dd>{chosen.comment_text}</dd><dt>Thời gian</dt><dd>{fmt(new Date())}</dd></dl><div className="actions"><button className="secondary" onClick={()=>setConfirming(false)}>Hủy</button><button className="danger-live" disabled={sending} onClick={dispatch}>{sending?'Đang chuyển job…':'Xác nhận gửi thật'}</button></div></div></div>}</>
}

function System({data,reload,tell}){
 const items=[['API',data.api],['Cơ sở dữ liệu',data.database],['Trình điều khiển Facebook',data.browserWorker],['n8n',data.n8n]];
 async function watchdog(){await req('/api/automation/watchdog',{method:'POST',body:'{}'});tell('Đã kiểm tra lại trình điều khiển');reload()}
 async function sessions(){try{await req('/api/automation/session-check',{method:'POST',body:'{}'});tell('Đã kiểm tra trạng thái đăng nhập');reload()}catch(e){tell(e.message)}}
 return <><section className="health-grid">{items.map(([name,item])=><article key={name}><div className={`health-dot ${statusKind(item?.status)}`}/><div><span>{name}</span><b>{statusText[item?.status]||'Chưa xác định'}</b>{item?.message&&<small>{item.message}</small>}</div></article>)}</section><Panel title="Chế độ gửi thực tế" description="Chỉ CHẠY THẬT khi cả ba lớp an toàn đều đã tắt chạy thử."><div className="mode-grid"><article><span>API</span><b>{data.apiDryRun?'CHẠY THỬ':'CHẠY THẬT'}</b></article><article><span>Worker</span><b>{data.workerDryRun===false?'CHẠY THẬT':'CHẠY THỬ'}</b></article><article><span>Chiến dịch {data.campaign?.name||''}</span><b>{data.campaignDryRun===false?'CHẠY THẬT':'CHẠY THỬ'}</b></article><article className={data.effectiveMode==='LIVE'?'live':'safe'}><span>Hiệu lực</span><b>{data.effectiveMode==='LIVE'?'CHẠY THẬT':'CHẠY THỬ'}</b></article></div>{data.configurationMismatch&&<div className="inline-warning"><AlertTriangle size={17}/><div><b>Cấu hình không đồng nhất</b><span>API, Worker và chiến dịch đang đặt khác chế độ.</span></div></div>}</Panel><Panel title="Các máy điều khiển Facebook" description="Tình trạng kết nối gần nhất của máy mở Facebook." action={<div className="actions"><button className="secondary" onClick={sessions}><Activity size={15}/>Kiểm tra đăng nhập</button><button onClick={watchdog}><Server size={15}/>Kiểm tra kết nối</button></div>}><Table heads={['Máy chạy','Trạng thái','Công việc hiện tại','Lần kiểm tra cuối']}>{data.workers?.length?data.workers.map(w=><tr key={w.id}><td><b>{w.name}</b></td><td><Badge value={w.health_status}/></td><td>{w.last_error||'Không có'}</td><td>{fmt(w.last_health_at)}</td></tr>):null}</Table></Panel></>
}
createRoot(document.getElementById('root')).render(<App/>);
