import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,AlertTriangle,CheckCircle2,ExternalLink,Pause,Play,Plus,RefreshCw,RotateCcw,Server,Square,WifiOff} from 'lucide-react';
import './styles.css';

const API=import.meta.env.VITE_API_BASE||'';
async function req(path,opt={}){let r;try{r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt})}catch{throw new Error('Không thể kết nối máy chủ')}if(r.status===204)return null;const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Máy chủ trả về lỗi ${r.status}`);return d}
const fmt=v=>v?new Date(v).toLocaleString('vi-VN'):'—';
const localInput=()=>{const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return d.toISOString().slice(0,16)};
const statusText={PENDING:'Chờ chạy',RETRY_DUE:'Chờ chạy lại',RUNNING:'Đang chạy',SUCCESS:'Thành công',FAILED:'Lỗi',SKIPPED:'Tạm dừng',PAUSED:'Tạm dừng',CANCELLED:'Đã hủy',UNKNOWN:'Chưa đăng nhập',READY:'Sẵn sàng',SESSION_EXPIRED:'Hết phiên đăng nhập',CHECKPOINT:'Cần xác minh',DISABLED:'Đang tắt',ONLINE:'Hoạt động',OFFLINE:'Mất kết nối',WARNING:'Cảnh báo'};
const statusKind=v=>({SUCCESS:'good',READY:'good',ONLINE:'good',RUNNING:'info',PENDING:'wait',RETRY_DUE:'wait',UNKNOWN:'wait',WARNING:'wait',FAILED:'bad',OFFLINE:'bad',SESSION_EXPIRED:'bad',CHECKPOINT:'bad',DISABLED:'muted',PAUSED:'muted',SKIPPED:'muted',CANCELLED:'muted'}[v]||'muted');
function Badge({value,label}){return <span className={`badge ${statusKind(value)}`}>{label||statusText[value]||value}</span>}
function Panel({title,description,action,children}){return <section className="panel"><div className="panel-head"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</div>{children}</section>}
function Table({heads,children,empty='Chưa có dữ liệu'}){return <div className="table-wrap"><table><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{children||<tr><td colSpan={heads.length} className="empty">{empty}</td></tr>}</tbody></table></div>}
function Field({label,hint,children}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}

function App(){
 const [tab,setTab]=useState('overview');const [data,setData]=useState({dash:{},campaigns:[],accounts:[],posts:[],templates:[],jobs:[],workers:[],system:null});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 async function load(){setLoading(true);setError('');try{const [dash,campaigns,accounts,posts,templates,jobs,workers,system]=await Promise.all(['/api/dashboard','/api/campaigns','/api/accounts','/api/posts','/api/templates','/api/jobs?limit=150','/api/workers','/api/system-status'].map(req));setData({dash,campaigns,accounts,posts,templates,jobs,workers,system})}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);const tell=m=>{setNotice(m);setTimeout(()=>setNotice(''),4000)};const nav=[['overview','Tổng quan'],['posts','Bài viết'],['accounts','Tài khoản Facebook'],['templates','Nội dung bình luận'],['campaigns','Chiến dịch'],['jobs','Hàng chờ'],['system','Trạng thái hệ thống']];
 return <div className="shell"><header><div><div className="brand">SIMI AUTOMATION</div><h1>Quản lý bình luận Facebook</h1><p>Điều phối nội dung, tài khoản và lịch bình luận tại một nơi.</p></div><button className="secondary" onClick={load} disabled={loading}><RefreshCw size={16} className={loading?'spin':''}/>Làm mới</button></header>{data.system?.dryRun&&<div className="trial"><AlertTriangle size={17}/><div><b>ĐANG CHẠY THỬ</b><span>Hệ thống chỉ mở bài và nhập nội dung, không gửi bình luận.</span></div></div>}{error&&<div className="alert error"><WifiOff size={17}/><div><b>Không thể kết nối máy chủ</b><span>{error}</span></div></div>}{notice&&<div className="alert success"><CheckCircle2 size={17}/>{notice}</div>}<nav>{nav.map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</nav><main>{loading&&!error&&<div className="loading">Đang tải dữ liệu…</div>}{!loading&&!error&&<>{tab==='overview'&&<Overview {...data}/>} {tab==='posts'&&<Posts {...data} reload={load} tell={tell}/>} {tab==='accounts'&&<Accounts rows={data.accounts} reload={load} tell={tell}/>} {tab==='templates'&&<Templates campaigns={data.campaigns} rows={data.templates} reload={load} tell={tell}/>} {tab==='campaigns'&&<Campaigns rows={data.campaigns} reload={load} tell={tell}/>} {tab==='jobs'&&<Jobs jobs={data.jobs} reload={load} tell={tell}/>} {tab==='system'&&<System data={data.system} reload={load} tell={tell}/>}</>}</main></div>
}
function Overview({dash,jobs}){const cards=[['Chiến dịch đang chạy',dash.activeCampaigns],['Tài khoản đang hoạt động',dash.activeAccounts],['Bài viết đang theo dõi',dash.enabledPosts],['Đang chờ bình luận',dash.pendingJobs],['Đã bình luận hôm nay',dash.successToday],['Lỗi hôm nay',dash.failedToday]];const recent=jobs.slice(0,12);return <><section className="cards">{cards.map(([l,v])=><article className="metric" key={l}><span>{l}</span><strong>{v??0}</strong></article>)}</section><Panel title="Hoạt động gần đây" description="Kết quả mới nhất từ dữ liệu thực của hệ thống."><Table heads={['Thời gian','Tài khoản','Bài viết','Nội dung','Trạng thái']}>{recent.length?recent.map(j=><tr key={j.id}><td>{fmt(j.finished_at||j.started_at||j.scheduled_at)}</td><td>{j.account_name}</td><td>{j.post_label||`Bài #${j.post_id}`}</td><td className="comment">{j.comment_text}</td><td><Badge value={j.status}/></td></tr>):null}</Table></Panel></>}

function Posts({posts,campaigns,accounts,reload,tell}){
 const [form,setForm]=useState({campaignId:'',postUrl:'',label:'',priority:100});const [schedule,setSchedule]=useState({postId:'',accountIds:[],startAt:localInput(),minGapMinutes:10,maxGapMinutes:30});const [preview,setPreview]=useState([]);const selected=useMemo(()=>posts.find(p=>String(p.id)===String(schedule.postId)),[posts,schedule.postId]);
 async function add(){try{await req('/api/posts',{method:'POST',body:JSON.stringify(form)});setForm({...form,postUrl:'',label:''});tell('Đã thêm bài viết');reload()}catch(e){tell(e.message)}}
 async function createSchedule(){if(!schedule.postId||!schedule.accountIds.length)return tell('Hãy chọn bài viết và ít nhất một tài khoản sẵn sàng');try{const result=await req(`/api/posts/${schedule.postId}/assign-accounts`,{method:'POST',body:JSON.stringify({...schedule,startAt:new Date(schedule.startAt).toISOString()})});setPreview(result.assignments.map(x=>({...x,name:accounts.find(a=>a.id===x.accountId)?.name||`Tài khoản #${x.accountId}`})));tell('Đã tạo lịch bình luận');reload()}catch(e){tell(e.message)}}
 async function toggle(p){await req(`/api/posts/${p.id}`,{method:'PATCH',body:JSON.stringify({isEnabled:!p.is_enabled})});reload()}
 return <><Panel title="Thêm bài viết" description="Khai báo bài Facebook cần theo dõi và bình luận." action={<button onClick={add}><Plus size={15}/>Thêm bài viết</button>}><div className="form-grid four"><Field label="Chiến dịch"><select value={form.campaignId} onChange={e=>setForm({...form,campaignId:e.target.value})}><option value="">Chọn chiến dịch</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Đường dẫn bài Facebook"><input placeholder="https://www.facebook.com/..." value={form.postUrl} onChange={e=>setForm({...form,postUrl:e.target.value})}/></Field><Field label="Tên gợi nhớ"><input placeholder="Group Gia Dụng - Bài máy hút bụi" value={form.label} onChange={e=>setForm({...form,label:e.target.value})}/></Field><Field label="Độ ưu tiên" hint="Mặc định 100"><input type="number" value={form.priority} onChange={e=>setForm({...form,priority:+e.target.value})}/></Field></div></Panel>
 <Panel title="Tạo lịch bình luận" description="Chọn các tài khoản sẽ tham gia; tài khoản chưa sẵn sàng sẽ không thể chọn." action={<button onClick={createSchedule}><Play size={15}/>Tạo lịch bình luận</button>}><div className="schedule"><div className="schedule-settings"><Field label="Bài viết"><select value={schedule.postId} onChange={e=>{setSchedule({...schedule,postId:e.target.value,accountIds:[]});setPreview([])}}><option value="">Chọn bài viết</option>{posts.filter(p=>p.is_enabled).map(p=><option key={p.id} value={p.id}>{p.label||p.post_url}</option>)}</select></Field><Field label="Bắt đầu từ"><input type="datetime-local" value={schedule.startAt} onChange={e=>setSchedule({...schedule,startAt:e.target.value})}/></Field><div className="two"><Field label="Khoảng cách tối thiểu (phút)"><input type="number" min="0" value={schedule.minGapMinutes} onChange={e=>setSchedule({...schedule,minGapMinutes:+e.target.value})}/></Field><Field label="Khoảng cách tối đa (phút)"><input type="number" min="0" value={schedule.maxGapMinutes} onChange={e=>setSchedule({...schedule,maxGapMinutes:+e.target.value})}/></Field></div>{selected&&<div className="selected"><b>{selected.label||'Bài viết chưa đặt tên'}</b><span>{selected.campaign_name}</span></div>}</div><div><h3>Tài khoản sẽ tham gia bình luận</h3><div className="account-grid">{accounts.map(a=>{const ready=a.session_status==='READY'&&a.is_active;const checked=schedule.accountIds.includes(a.id);return <label className={`${checked?'checked ':''}${!ready?'disabled':''}`} key={a.id}><input type="checkbox" disabled={!ready} checked={checked} onChange={e=>setSchedule({...schedule,accountIds:e.target.checked?[...schedule.accountIds,a.id]:schedule.accountIds.filter(id=>id!==a.id)})}/><div><b>{a.name}</b><small>{a.profile_key}</small></div><Badge value={a.is_active?a.session_status:'DISABLED'}/></label>})}</div>{preview.length>0&&<div className="preview"><h3>Lịch vừa tạo</h3>{preview.map(x=><div key={x.accountId}><span>{x.name}</span><b>→ {fmt(x.scheduledAt)}</b></div>)}</div>}</div></div></Panel>
 <Panel title="Danh sách bài viết"><Table heads={['Bài viết','Chiến dịch','Số tài khoản','Đã bình luận','Đang chờ','Độ ưu tiên','Thao tác']}>{posts.length?posts.map(p=><tr key={p.id}><td><b>{p.label||'Chưa đặt tên'}</b><div className="muted truncate">{p.post_url}</div></td><td>{p.campaign_name}</td><td>{p.account_count}</td><td>{p.success_count}</td><td>{p.pending_count}</td><td>{p.priority}</td><td><div className="actions"><a className="icon-btn" href={p.post_url} target="_blank" rel="noreferrer"><ExternalLink size={15}/></a><button className="tiny secondary" onClick={()=>toggle(p)}>{p.is_enabled?'Tạm dừng':'Bật lại'}</button></div></td></tr>):null}</Table></Panel></>
}

function Accounts({rows,reload,tell}){const [form,setForm]=useState({name:'',profileKey:'',dailyLimitOverride:''});async function add(){try{await req('/api/accounts',{method:'POST',body:JSON.stringify(form)});setForm({name:'',profileKey:'',dailyLimitOverride:''});tell('Đã thêm tài khoản Facebook');reload()}catch(e){tell(e.message)}}async function toggle(a){await req(`/api/accounts/${a.id}`,{method:'PATCH',body:JSON.stringify({isActive:!a.is_active})});reload()}return <Panel title="Tài khoản Facebook" description="Mỗi tài khoản liên kết với một phiên trình duyệt riêng." action={<button onClick={add}><Plus size={15}/>Thêm tài khoản</button>}><div className="form-grid three"><Field label="Tên tài khoản"><input placeholder="Facebook SIMI 01" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Mã phiên trình duyệt" hint="Mã này dùng để liên kết với phiên Facebook đã đăng nhập trên máy chạy Trình điều khiển Facebook."><input placeholder="simi_fb_01" value={form.profileKey} onChange={e=>setForm({...form,profileKey:e.target.value})}/></Field><Field label="Giới hạn bình luận/ngày"><input type="number" min="1" placeholder="10" value={form.dailyLimitOverride} onChange={e=>setForm({...form,dailyLimitOverride:e.target.value})}/></Field></div><Table heads={['Tên tài khoản','Mã phiên','Trạng thái đăng nhập','Số bài được gán','Đã chạy hôm nay','Giới hạn/ngày','Thao tác']}>{rows.length?rows.map(a=><tr key={a.id}><td><b>{a.name}</b></td><td><code>{a.profile_key}</code></td><td><Badge value={a.is_active?a.session_status:'DISABLED'}/></td><td>{a.assigned_posts}</td><td>{a.success_today}</td><td>{a.daily_limit_override||'Theo chiến dịch'}</td><td><button className="tiny secondary" onClick={()=>toggle(a)}>{a.is_active?'Tắt':'Bật lại'}</button></td></tr>):null}</Table></Panel>}

function Templates({campaigns,rows,reload,tell}){const [form,setForm]=useState({campaignId:'',content:'',weight:1});async function add(){try{await req('/api/templates',{method:'POST',body:JSON.stringify(form)});setForm({...form,content:''});tell('Đã thêm nội dung bình luận');reload()}catch(e){tell(e.message)}}return <Panel title="Kho nội dung bình luận" description="Nội dung đã duyệt sẽ được phân bổ theo mức ưu tiên." action={<button onClick={add}><Plus size={15}/>Thêm nội dung</button>}><div className="form-grid template"><Field label="Chiến dịch"><select value={form.campaignId} onChange={e=>setForm({...form,campaignId:e.target.value})}><option value="">Chọn chiến dịch</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Nội dung bình luận"><input placeholder="Nhập nội dung đã được duyệt" value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></Field><Field label="Tần suất ưu tiên"><input type="number" min="1" value={form.weight} onChange={e=>setForm({...form,weight:+e.target.value})}/></Field></div><Table heads={['Nội dung','Chiến dịch','Mức ưu tiên','Số lần đã dùng','Trạng thái']}>{rows.length?rows.map(x=><tr key={x.id}><td className="comment">{x.content}</td><td>{x.campaign_name}</td><td>{x.weight}</td><td>{x.usage_count}</td><td><Badge value={x.is_active?'READY':'DISABLED'} label={x.is_active?'Đang sử dụng':'Đang tắt'}/></td></tr>):null}</Table></Panel>}

function Campaigns({rows,reload,tell}){const [form,setForm]=useState({name:'',cooldownMinutes:180,maxCommentsPerAccountPerDay:8,dryRun:true});async function add(){try{await req('/api/campaigns',{method:'POST',body:JSON.stringify(form)});setForm({...form,name:''});tell('Đã tạo chiến dịch');reload()}catch(e){tell(e.message)}}async function patch(id,body){await req(`/api/campaigns/${id}`,{method:'PATCH',body:JSON.stringify(body)});reload()}return <Panel title="Chiến dịch" description="Quản lý giới hạn và chế độ vận hành cho từng đợt bình luận." action={<button onClick={add}><Plus size={15}/>Tạo chiến dịch</button>}><div className="form-grid four"><Field label="Tên chiến dịch"><input placeholder="Chiến dịch 10.10" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Thời gian nghỉ giữa các lượt (phút)"><input type="number" value={form.cooldownMinutes} onChange={e=>setForm({...form,cooldownMinutes:+e.target.value})}/></Field><Field label="Giới hạn bình luận/ngày"><input type="number" value={form.maxCommentsPerAccountPerDay} onChange={e=>setForm({...form,maxCommentsPerAccountPerDay:+e.target.value})}/></Field><Field label="Chế độ thử nghiệm" hint="Chỉ nhập nội dung, không gửi bình luận."><label className="switch"><input type="checkbox" checked={form.dryRun} onChange={e=>setForm({...form,dryRun:e.target.checked})}/><span>{form.dryRun?'Đang bật':'Đang tắt'}</span></label></Field></div><Table heads={['Chiến dịch','Giới hạn/ngày','Chế độ thử nghiệm','Trạng thái','Khung giờ','Thao tác']}>{rows.length?rows.map(c=><tr key={c.id}><td><b>{c.name}</b></td><td>{c.max_comments_per_account_per_day}</td><td><Badge value={c.dry_run?'WARNING':'READY'} label={c.dry_run?'Chạy thử':'Chạy thật'}/></td><td><Badge value={c.is_active?'READY':'DISABLED'} label={c.is_active?'Đang chạy':'Tạm dừng'}/></td><td>{c.window_count}</td><td><div className="actions"><button className="tiny secondary" onClick={()=>patch(c.id,{dryRun:!c.dry_run})}>{c.dry_run?'Cho phép gửi':'Bật chạy thử'}</button><button className="tiny secondary" onClick={()=>patch(c.id,{isActive:!c.is_active})}>{c.is_active?'Tạm dừng':'Bật lại'}</button></div></td></tr>):null}</Table></Panel>}

function Jobs({jobs,reload,tell}){async function manual(j){try{await req('/api/automation/manual',{method:'POST',body:JSON.stringify({postId:j.post_id,accountId:j.account_id})});tell('Đã đưa lượt bình luận lên chạy ngay');reload()}catch(e){tell(e.message)}}async function action(j,a){try{await req(`/api/jobs/${j.id}/action`,{method:'POST',body:JSON.stringify({action:a})});tell('Đã cập nhật hàng chờ');reload()}catch(e){tell(e.message)}}return <Panel title="Hàng chờ bình luận" description="Theo dõi các nội dung sắp chạy và xử lý khi cần."><Table heads={['Thời gian dự kiến','Tài khoản','Bài viết','Nội dung','Trạng thái','Thao tác']}>{jobs.length?jobs.map(j=><tr key={j.id}><td>{fmt(j.scheduled_at)}</td><td><b>{j.account_name}</b><div className="muted">{j.profile_key}</div></td><td>{j.post_label||`Bài #${j.post_id}`}</td><td className="comment">{j.comment_text}</td><td><Badge value={j.status}/>{j.error_code&&<div className="error-code">{j.error_code}</div>}</td><td><div className="actions">{['PENDING','RETRY_DUE'].includes(j.status)&&<><button className="tiny" onClick={()=>manual(j)}><Play size={12}/>Chạy ngay</button><button className="tiny secondary" onClick={()=>action(j,'pause')}><Pause size={12}/>Tạm dừng</button><button className="tiny danger" onClick={()=>action(j,'cancel')}><Square size={12}/>Hủy</button></>}{j.status==='PAUSED'&&<button className="tiny" onClick={()=>action(j,'resume')}><Play size={12}/>Tiếp tục</button>}{['FAILED','CANCELLED'].includes(j.status)&&<button className="tiny" onClick={()=>action(j,'retry')}><RotateCcw size={12}/>Chạy lại</button>}</div></td></tr>):null}</Table></Panel>}

function System({data,reload,tell}){const items=[['API',data.api],['Cơ sở dữ liệu',data.database],['Trình điều khiển Facebook',data.browserWorker],['n8n',data.n8n]];async function watchdog(){await req('/api/automation/watchdog',{method:'POST',body:'{}'});tell('Đã kiểm tra lại trình điều khiển');reload()}async function sessions(){try{await req('/api/automation/session-check',{method:'POST',body:'{}'});tell('Đã kiểm tra trạng thái đăng nhập');reload()}catch(e){tell(e.message)}}return <><section className="health-grid">{items.map(([name,item])=><article key={name}><div className={`health-dot ${statusKind(item?.status)}`}/><div><span>{name}</span><b>{statusText[item?.status]||'Chưa xác định'}</b>{item?.message&&<small>{item.message}</small>}</div></article>)}</section><Panel title="Các máy điều khiển Facebook" description="Tình trạng kết nối gần nhất của máy mở Facebook." action={<div className="actions"><button className="secondary" onClick={sessions}><Activity size={15}/>Kiểm tra đăng nhập</button><button onClick={watchdog}><Server size={15}/>Kiểm tra kết nối</button></div>}><Table heads={['Máy chạy','Trạng thái','Công việc hiện tại','Lần kiểm tra cuối']}>{data.workers?.length?data.workers.map(w=><tr key={w.id}><td><b>{w.name}</b></td><td><Badge value={w.health_status}/></td><td>{w.last_error||'Không có'}</td><td>{fmt(w.last_health_at)}</td></tr>):null}</Table></Panel></>}
createRoot(document.getElementById('root')).render(<App/>);
